export const ENTROPY_SYSTEM_CONSTANTS = {
  // entropy score
  MIN_ENTROPY_SCORE: 0,
  MAX_ENTROPY_SCORE: 100,
  DELTA_PER_MINUTE: 0.08,
  INITIAL_ENTROPY_SCORE: 80,
  ENTROPY_SCORE_UPDATE_INTERVAL_MS: 60 * 1000,

  ENTROPY_SCORE: {
    VERY_LOW_MAX: 20,
    LOW_MAX: 40,
    MEDIUM_MAX: 60,
    HIGH_MAX: 80,
    VERY_HIGH_MAX: 100,
  },
} as const;

export const RENDER_CONSTANTS = {
  // particle color range
  MAX_COLOR_VALUE: 255,
  MIN_COLOR_VALUE: 140,
} as const;
